apiVersion: v1
kind: Service
metadata:
  labels:
   hypercloud: claim-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
   hypercloud: claim-operator
